return {
	[0] = 	{nil, 										"none", 	"NONE"},
			{"COLOR_PROFILE_CLASSICSTYLE_PURP", 		"purple",	"PURPLE"},
			{"COLOR_PROFILE_CLASSICSTYLE_STEL", 		"steel",	"STEEL"},
			{"COLOR_PROFILE_CLASSICSTYLE_CYAN", 		"cyan",		"CYAN"},
			{"COLOR_PROFILE_CLASSICSTYLE_TEAL", 		"teal",		"TEAL"},
			{"COLOR_PROFILE_CLASSICSTYLE_APPL", 		"apple",	"APPLE"},
			{"COLOR_PROFILE_CLASSICSTYLE_REVR", 		"reverse",	"REVERSE"},			

			{"COLOR_PROFILE_CLASSICSTYLE_HC", 			"hc", 		"HIGH-CONTRAST"},
			{"COLOR_PROFILE_CLASSICSTYLE_PURPHC", 		"hcpurple",	"HIGH-CONTRAST PURPLE"},
			{"COLOR_PROFILE_CLASSICSTYLE_STELHC", 		"hcsteel",	"HIGH-CONTRAST STEEL"},
			{"COLOR_PROFILE_CLASSICSTYLE_CYANHC", 		"hccyan",	"HIGH-CONTRAST CYAN"},
			{"COLOR_PROFILE_CLASSICSTYLE_TEALHC", 		"hcteal",	"HIGH-CONTRAST TEAL"},
			{"COLOR_PROFILE_CLASSICSTYLE_APPLHC", 		"hcapple",	"HIGH-CONTRAST APPLE"},
			{"COLOR_PROFILE_CLASSICSTYLE_REVRHC", 		"hcreverse","HIGH-CONTRAST REVERSE"},			
}