local picks = {
	[MT_ATTRACT_BOX] = true,
	[MT_ARMAGEDDON_BOX] = true,
	[MT_WHIRLWIND_BOX] = true,
	[MT_ELEMENTAL_BOX] = true,
	[MT_FORCE_BOX] = true,
	[MT_ATTRACT_GOLDBOX] = true,
	[MT_ARMAGEDDON_GOLDBOX] = true,
	[MT_WHIRLWIND_GOLDBOX] = true,
	[MT_ELEMENTAL_GOLDBOX] = true,
	[MT_FORCE_GOLDBOX] = true,
}

local sets = {
	[1] = { -- Sonic 1
		[MT_ATTRACT_BOX] = MT_PITY_BOX,
		[MT_ARMAGEDDON_BOX] = MT_PITY_BOX,
		[MT_WHIRLWIND_BOX] = MT_PITY_BOX,
		[MT_ELEMENTAL_BOX] = MT_PITY_BOX,
		[MT_FORCE_BOX] = MT_PITY_BOX,
		[MT_ATTRACT_GOLDBOX] = MT_PITY_GOLDBOX,
		[MT_ARMAGEDDON_GOLDBOX] = MT_PITY_GOLDBOX,
		[MT_WHIRLWIND_GOLDBOX] = MT_PITY_GOLDBOX,
		[MT_ELEMENTAL_GOLDBOX] = MT_PITY_GOLDBOX,
		[MT_FORCE_GOLDBOX] = MT_PITY_GOLDBOX,
	},

	[2] = { -- Sonic 3
		[MT_ATTRACT_BOX] = MT_THUNDERCOIN_BOX,
		[MT_ARMAGEDDON_BOX] = MT_BUBBLEWRAP_BOX,
		[MT_WHIRLWIND_BOX] = MT_THUNDERCOIN_BOX,
		[MT_ELEMENTAL_BOX] = MT_BUBBLEWRAP_BOX,
		[MT_FORCE_BOX] = MT_FLAMEAURA_BOX,
		[MT_ATTRACT_GOLDBOX] = MT_THUNDERCOIN_GOLDBOX,
		[MT_ARMAGEDDON_GOLDBOX] = MT_BUBBLEWRAP_GOLDBOX,
		[MT_WHIRLWIND_GOLDBOX] = MT_THUNDERCOIN_GOLDBOX,
		[MT_ELEMENTAL_GOLDBOX] = MT_BUBBLEWRAP_GOLDBOX,
		[MT_FORCE_GOLDBOX] = MT_FLAMEAURA_GOLDBOX,
	},

	[3] = { -- Mania
		[MT_ATTRACT_BOX] = MT_FLAMEAURA_BOX,
		[MT_ARMAGEDDON_BOX] = MT_PITY_BOX,
		[MT_WHIRLWIND_BOX] = MT_THUNDERCOIN_BOX,
		[MT_ELEMENTAL_BOX] = MT_BUBBLEWRAP_BOX,
		[MT_FORCE_BOX] = MT_PITY_BOX,
		[MT_ATTRACT_GOLDBOX] = MT_FLAMEAURA_GOLDBOX,
		[MT_ARMAGEDDON_GOLDBOX] = MT_PITY_GOLDBOX,
		[MT_WHIRLWIND_GOLDBOX] = MT_THUNDERCOIN_GOLDBOX,
		[MT_ELEMENTAL_GOLDBOX] = MT_BUBBLEWRAP_GOLDBOX,
		[MT_FORCE_GOLDBOX] = MT_PITY_GOLDBOX,
	},
}

return {picks, sets}